#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Parity-harness generator for the Lua conjugator port.

Runs the Python reference engine (cli-version/engine.py) over a fixed sample set
and emits three files consumed by run_test.lua:

  samples.txt      one token per line (the harness input).
  expected.lua     `return { ... }` — engine.conjugate_field("「token」") per line.
  pos_fixture.lua  the exact JMdict POS rows (classes + common flag) the engine
                   touched while producing the expected output, so the Lua port
                   classifies against identical data without needing SQLite.

The Lua side (run_test.lua) recomputes conjugate_field for each token and diffs
against expected.lua; any difference is a port-fidelity failure.

Usage (from the plugin's tools/ dir, Python 3.9+):
    python3 gen_expected.py
"""

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
# tools -> japanese.koplugin -> plugins -> koreader-master -> cli-version
CLI_DIR = os.path.normpath(os.path.join(HERE, "..", "..", "..", ".."))
sys.path.insert(0, CLI_DIR)

import engine  # noqa: E402  (imported after the sys.path tweak)

# Sample tokens: the acceptance set plus the documented edge cases.  Keep these
# as bare surface forms; the harness wraps each as a single 「…」 field.
SAMPLES = [
    # --- acceptance criteria ---
    "食べさせられました", "行かなかった", "高くない", "静かじゃない", "来られた",
    "勉強しました", "できます", "よさそう", "本", "を",
    # --- verbs: classes & irregulars ---
    "する", "来る", "くる", "飲む", "行く", "食べる", "見える", "論ずる", "過ぎる",
    "すぎる", "なさいます", "いらっしゃいます",
    # --- already-derived (kept, not re-derived) ---
    "させられる", "飲める", "飲ませる", "できる",
    # --- inflected inputs that deinflect ---
    "飲まない", "来ない", "こない", "飛んだ", "よくなかった", "食べさせられた",
    # --- i-adjectives ---
    "大きい", "いい", "かっこいい", "高い",
    # --- na-adjectives / nouns / copula ---
    "静か", "学生でした", "大きいです", "勉強", "だ", "です", "じゃない",
    "でしょうか",
    # --- na-like auxiliaries ---
    "ようだ", "そうだ", "みたい",
    # --- particles / pronouns / stoplist fragments / non-conjugating ---
    "どうか", "それ", "私", "らしい", "たい", "ね", "よ",
    "ます", "ません", "ありません", "によって", "かった", "ない",
    # --- multi-token field (dedupe / original labelling across tokens) ---
    "「する」「ようだ」「ありません」",
]


def field(line):
    return line if line.startswith("「") else "「" + line + "」"


def lua_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main():
    # Record every POS lookup the engine performs so the Lua fixture is exact.
    rec_classes, rec_common = {}, {}
    orig_classes = engine.DICT.classes
    orig_common = engine.DICT.common

    def classes_spy(surface):
        r = orig_classes(surface)
        if r:
            rec_classes[surface] = r
        return r

    def common_spy(surface):
        r = orig_common(surface)
        if r:
            rec_common[surface] = True
        return r

    engine.DICT.classes = classes_spy
    engine.DICT.common = common_spy

    expected = [engine.conjugate_field(field(line)) for line in SAMPLES]

    with open(os.path.join(HERE, "samples.txt"), "w", encoding="utf-8") as fh:
        fh.write("\n".join(SAMPLES) + "\n")

    with open(os.path.join(HERE, "expected.lua"), "w", encoding="utf-8") as fh:
        fh.write("-- Generated by gen_expected.py — engine.conjugate_field per sample.\n")
        fh.write("return {\n")
        for line in expected:
            fh.write("  " + lua_str(line) + ",\n")
        fh.write("}\n")

    with open(os.path.join(HERE, "pos_fixture.lua"), "w", encoding="utf-8") as fh:
        fh.write("-- Generated by gen_expected.py — JMdict POS rows the engine touched.\n")
        fh.write("return {\n  classes = {\n")
        for surface in sorted(rec_classes):
            classes = ", ".join(lua_str(c) for c in rec_classes[surface])
            fh.write("    [" + lua_str(surface) + "] = { " + classes + " },\n")
        fh.write("  },\n  common = {\n")
        for surface in sorted(rec_common):
            fh.write("    [" + lua_str(surface) + "] = true,\n")
        fh.write("  },\n}\n")

    print("wrote samples.txt ({} samples), expected.lua, pos_fixture.lua "
          "({} class rows, {} common rows)".format(
              len(SAMPLES), len(rec_classes), len(rec_common)))


if __name__ == "__main__":
    main()
